-- require('onedark').setup {
--     style = 'deep'
-- }
-- 
-- function ColorMyPencil(color)
-- 	color = color or "onedark"
-- 	vim.cmd("colorscheme onedark")
-- 	-- Transparent background settings
-- 	vim.cmd [[
-- 	hi Normal guibg=NONE ctermbg=NONE
-- 	hi NonText guibg=NONE ctermbg=NONE
-- 	hi NormalNC guibg=NONE ctermbg=NONE
-- 	hi SpecialKey guibg=NONE ctermbg=NONE
-- 	hi StatusLine guibg=NONE ctermbg=NONE
-- 	hi StatusLineNC guibg=NONE ctermbg=NONE
-- 	hi TabLine guibg=NONE ctermbg=NONE
-- 	hi TabLineFill guibg=NONE ctermbg=NONE
-- 	hi TabLineSel guibg=NONE ctermbg=NONE
-- 	hi VertSplit guibg=NONE ctermbg=NONE
-- 	hi SignColumn guibg=NONE ctermbg=NONE
-- 	hi EndOfBuffer guibg=NONE ctermbg=NONE
-- 	hi FloatBorder guibg=NONE ctermbg=NONE
-- 	hi Pmenu guibg=NONE ctermbg=NONE
-- 	hi PmenuSel guibg=NONE ctermbg=NONE
-- 	hi PmenuSbar guibg=NONE ctermbg=NONE
-- 	hi PmenuThumb guibg=NONE ctermbg=NONE
-- 	]]
-- 
-- end
-- 
-- ColorMyPencil()
